[tox]
envlist =
    lint
    py{310,311,312,313,314}

[testenv]
deps =
    pytest
    setuptools<82
commands =
    pytest {posargs} tests

[testenv:lint]
deps =
    flake8
skip-install = true
commands =
    flake8 src tests

[flake8]
extend-ignore = E501
