[tox]
envlist =
    lint
    py{310,311,312,313,314}

[testenv]
deps =
    pytest
commands =
    pytest {posargs} tests

[testenv:lint]
deps =
    pre-commit
skip-install = true
commands =
    pre-commit run --all-files --show-diff-on-failure

[flake8]
extend-ignore = E501
